# Generated by Django 3.1.1 on 2020-09-18 00:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursestudent',
            unique_together={('course_user', 'course')},
        ),
    ]
