# Generated by Django 3.1.1 on 2020-09-18 14:06

import courses.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200918_0705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order'], 'verbose_name': 'Тема/Контент', 'verbose_name_plural': 'Темы/Контент'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.ImageField(default='static/img/js.png', upload_to='icons', verbose_name='Иконки курсов'),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(default='', max_length=500, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=courses.fields.OrderField(blank=True, verbose_name='Очередной номер раздела'),
        ),
    ]
